Budget-tracker/config/routes.rb
Rails.application.routes.draw do
  resources :budgets
  root "budgets#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Budget-tracker/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Budget-tracker/app/models/budget.rb
class Budget < ApplicationRecord

	def home
		self.house / self.income
	end
	def electric
		self.elec / self.income
	end
	def creditc
		self.credit / self.income
	end
	def gasoline
		self.gas / self.income
	end
	def truck
		self.car / self.income
	end
	def insurance
		self.insur / self.income
	end
	def watering
		self.water / self.income
	end
	def spending
		self.money / self.income
	end
end

Budget-tracker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Budget-tracker/app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :set_budget, only: [:show, :edit, :update, :destroy]

  # GET /budgets
  # GET /budgets.json
  def index
    @budgets = Budget.all
  end

  # GET /budgets/1
  # GET /budgets/1.json
  def show
  end

  # GET /budgets/new
  def new
    @budget = Budget.new
  end

  # GET /budgets/1/edit
  def edit
  end

  # POST /budgets
  # POST /budgets.json
  def create
    @budget = Budget.new(budget_params)

    respond_to do |format|
      if @budget.save
        format.html { redirect_to @budget, notice: 'Budget was successfully created.' }
        format.json { render :show, status: :created, location: @budget }
      else
        format.html { render :new }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /budgets/1
  # PATCH/PUT /budgets/1.json
  def update
    respond_to do |format|
      if @budget.update(budget_params)
        format.html { redirect_to @budget, notice: 'Budget was successfully updated.' }
        format.json { render :show, status: :ok, location: @budget }
      else
        format.html { render :edit }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budgets/1
  # DELETE /budgets/1.json
  def destroy
    @budget.destroy
    respond_to do |format|
      format.html { redirect_to budgets_url, notice: 'Budget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budget
      @budget = Budget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def budget_params
      params.require(:budget).permit(:income, :house, :elec, :credit, :gas, :car, :insur, :water, :money)
    end
end

Budget-tracker/app/helpers/application_helper.rb
module ApplicationHelper
end

Budget-tracker/app/helpers/budgets_helper.rb
module BudgetsHelper
end

Budget-tracker/app/views/budgets/_form.html.erb
<%= form_for(budget) do |f| %>
  <% if budget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(budget.errors.count, "error") %> prohibited this budget from being saved:</h2>

      <ul>
      <% budget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :income %>
    <%= f.text_field :income %>
  </div>

  <div class="field">
    <%= f.label :house %>
    <%= f.text_field :house %>
  </div>

  <div class="field">
    <%= f.label :elec %>
    <%= f.text_field :elec %>
  </div>

  <div class="field">
    <%= f.label :credit %>
    <%= f.text_field :credit %>
  </div>

  <div class="field">
    <%= f.label :gas %>
    <%= f.text_field :gas %>
  </div>

  <div class="field">
    <%= f.label :car %>
    <%= f.text_field :car %>
  </div>

  <div class="field">
    <%= f.label :insur %>
    <%= f.text_field :insur %>
  </div>

  <div class="field">
    <%= f.label :water %>
    <%= f.text_field :water %>
  </div>

  <div class="field">
    <%= f.label :money %>
    <%= f.text_field :money %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Budget-tracker/app/views/budgets/edit.html.erb
<h1>Editing Budget</h1>

<%= render 'form', budget: @budget %>

<%= link_to 'Show', @budget %> |
<%= link_to 'Back', budgets_path %>

Budget-tracker/app/views/budgets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Budgets</h1>

<table>
  <thead>
    <tr>
      <th>Income</th>
      <th>House</th>
      <th>Elec</th>
      <th>Credit</th>
      <th>Gas</th>
      <th>Car</th>
      <th>Insur</th>
      <th>Water</th>
      <th>Money</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @budgets.each do |budget| %>
      <tr>
        <td><%= budget.income %></td>
        <td><%= budget.house %></td>
        <td><%= budget.elec %></td>
        <td><%= budget.credit %></td>
        <td><%= budget.gas %></td>
        <td><%= budget.car %></td>
        <td><%= budget.insur %></td>
        <td><%= budget.water %></td>
        <td><%= budget.money %></td>
        <td><%= link_to 'Show', budget %></td>
        <td><%= link_to 'Edit', edit_budget_path(budget) %></td>
        <td><%= link_to 'Destroy', budget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Budget', new_budget_path %>

Budget-tracker/app/views/budgets/new.html.erb
<h1>New Budget</h1>

<%= render 'form', budget: @budget %>

<%= link_to 'Back', budgets_path %>

Budget-tracker/app/views/budgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>House:</strong>
  <%= @budget.home %>
</p>

<p>
  <strong>Elec:</strong>
  <%= @budget.electric %>
</p>

<p>
  <strong>Credit:</strong>
  <%= @budget.creditc %>
</p>

<p>
  <strong>Gas:</strong>
  <%= @budget.gasoline %>
</p>

<p>
  <strong>Car:</strong>
  <%= @budget.truck %>
</p>

<p>
  <strong>Insur:</strong>
  <%= @budget.insurance %>
</p>

<p>
  <strong>Water:</strong>
  <%= @budget.watering %>
</p>

<p>
  <strong>Money:</strong>
  <%= @budget.spending %>
</p>

<%= link_to 'Edit', edit_budget_path(@budget) %> |
<%= link_to 'Back', budgets_path %>

Budget-tracker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetTracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>